# Generated by Django 5.1.7 on 2025-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_codeupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeupload',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='codeupload',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
