# Generated by Django 5.1.7 on 2025-04-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_codeanalysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeanalysisresult',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
