# Generated by Django 5.1.7 on 2025-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_codeanalysisresult_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeanalysisresult',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
